### ISSUE TITLE
`#[test_script]` for unit testing

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1832]
Add a `#[test_script]` that defines a script with no input parameters and an optional output value. Only valid for `contract`s. The compiler must:

1. compile the contract entirely, then
1. compile each script test independently, allowing implicit use of any ABI declarations the contract implements, then
1.  output each script test's compiled output to a different `.bin` file.

This will be sufficient for downstream tools such as `forc test` to pick them up and automatically run them, as a first step to in-language testing.

---

*Following added by @mitchmindtree.*

## TODO

- [x] #2979.
- [x] #2980.
    - [x] Support the `#[test]` attribute on Sway functions.
    - [x] Add `#[test]` to set of known attributes.
    - [x] Update original `compile` function (i.e. `forc build`) to ignore all `#[test]` functions. Likely best done during `convert_parse_tree`.
- [ ] Update `sway-core` to provide an alternative to `compile` called `compile_tests` that lazily generates bytecode for each test function, treating each as an entry point.
    1. Type check full program (including `#[test]` functions).
    2. Add `#[test]` functions as entry points for dead code analysis.
    3. Generate bytecode for each `#[test]` function entrypoint.
- [ ] Add a `forc test` command that executes the bytecode.
- [ ] Add a `forc check --tests` flag for use by `sway-lsp` to type-check all tests (without codegen or running them).

## Follow-up

- Refactor E2E tests to take advantage of new `#[test]` feature where possible.
- Consider moving some std lib unit tests back to std library and use `#[test]`, rather than in E2E tests?
- Introduce `[dev-dependencies]` table to `Forc.toml`.

**Comment by mitchmindtree** [comment]
@adlerjohn are you happy to go with `#[test]` for this over `#[test_script]`? I don't recall if there was a particular motivation for `#[test_script]` instead :thinking:

**Comment by adlerjohn** [comment]
The motivation is that there needs to be a way to write tests that involve running a script transaction and calling one or more ABI methods, and a way to run a unit test that `just happens` without having to go through a transaction.

**Comment by mitchmindtree** [comment]
Ahhh yes, perhaps we could go with something like this?

- `#[test]` - base test declaration, "just happens".
- `#[test(script)]` - indicates a script transaction is required in order to call one or more ABI methods.

This way we only need to check for `test` throughout the compiler when doing things like checking for extra entry points, testing for known attribute names, etc. Then we can just do something like `.contains("script")` on the inner set to determine if a transaction is required.

**Comment by adlerjohn** [comment]
Interesting alternative. I'm impartial either way, so long as there's the two options. Might be a good time to get some bikeshedding comments in!
