### ISSUE TITLE
[Tracking] `forc` debugger command

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2350]
## Overview

The `fuel-debugger` is a CLI tool that acts as a FVM client and provides runtime debugging support for FVM bytecode.

We should provide a `forc debugger` (or `forc dbg`?) plugin that wraps and extends `fuel-debugger` with sway/forc-specific functionality.

This might include:

- Configuration via forc manifest.
- Debug build profile awareness.
- Automatically sources contracts, bytecode from `out/`.
- Ensures target is build before running the debugger (or alternatively, recommends running `forc build` if `out/` artifacts don't exist yet).

https://github.com/FuelLabs/fuel-debugger/issues/15#issuecomment-1189807099

## TODO

- [ ] Address blocking language issues:
    - #2055.
    - #1527.
- [x] Create a `forc-dbg` crate under `plugins/`. *TODO: Break this into sub-issues*.
- [x] #1864.
- [x] Ensure docs automatically generate correctly under forc chapter in sway book.
- [x] Ensure plugin is tested under CI.
