### ISSUE TITLE
Some usability issues around `abi` and `Contract`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2397]
## Tracking sub-issues mentioned below

- [x] Self `impl` instead of `impl` ABI for `Contract` (fixed in #3021)
- [x] Mismatch in return types (fixed in #3022)
- [x] Repeated ABI declarations (#3661)
- [x] Multiple definitions of ABI methods (fixed in #3031)
- [x] `self` inside ABI function signature (#3662)

## Detailed description

Below are some examples that should not compile but do. I bundled those together in the same issue because they are somewhat related and there may be others. Whoever takes this on should also think about other corner cases that are not covered below.

### Self `impl` instead of `impl` ABI for `Contract`
```rust
contract;

abi MyContract {
    fn foo();
}

impl Contract { // self impl for a `Contract`?
    fn foo() {
    }
}
```

### Mismatch in return types
Interestingly this is only a problem for integer types. I still don't think this should compile (Similar playground [link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3ad4f1d1c04611ef4920b9a2c364a178))
```rust
contract;

abi MyContract {
    fn foo() -> u32;
}

impl MyContract for Contract {
    fn foo() -> u64 {
        0 
    }
}
```
Traits in Sway have the same problem btw. The following should not compile but does:
```rust
trait T {
    fn foo() -> u64;
}

struct S {
    x: u64
}

impl T for S {
    fn foo() -> u32 {
        0
    }
}
```
This also seems to be a problem in this situation which compiles but shouldn't:
```rust
contract;

abi MyContract {
    fn foo()-> u64;
}

impl Contract {
    fn foo() { // No return type here
    }
}
```

### Repeated `abi` declarations:
The following compiles but I don't expect it to:
```rust
contract;

abi MyContract {
    fn foo() -> u64;
}

abi MyContract {
    fn bar() -> u64;
}
```

### Multiple definitions of `abi` methods
Example:
```rust
contract;

abi MyContract {
    fn foo() -> u64;
}

impl MyContract for Contract {
    fn foo() -> u64 {
        0
    }
}

impl MyContract for Contract {
    fn foo() -> u64 {
        0
    }
}
```
Multiple `impl` blocks for the same type or trait should be allowed but they should not allow redefinition of methods. This applies for ABIs, regular traits, and types.

### `self` inside ABI function signature
ABI function should not accept `self` as the first argument.
```rust
contract;

abi MyContract {
    fn foo(self);
}
```

**Comment by otrho** [comment]
Oh wow, these are quite surprising.  OTOH, they aren't since all our tests are written by humans.  We should consider using a fuzzer to come up with these sorts of examples.

**Comment by emilyaherbert** [comment]
Sorry @anton-trunov I put myself under the assigned section on accident.

**Comment by mohammadfawaz** [comment]
Looks like all the tasks are now complete. Closing.
