### ISSUE TITLE
[Tracking] Integrate wallet support into `forc` client commands (i.e. `deploy`, `run`)

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2413]
Deploying contracts and running scripts on the Fuel VM will cost gas.

We need a way to enable users of `forc deploy` and `forc run` to sign transactions from a local wallet.

To achieve this, we can take advantage of [the SDK's wallet API](https://fuellabs.github.io/fuels-rs/v0.18.0/getting-started/managing-wallets.html).

We will likely need to work with and simultaneously develop [the `forc-wallet` plugin](https://github.com/FuelLabs/forc-wallet) to ensure a smooth CLI wallet UX from the creation of a wallet all the way through to paying for transactions.

We should first help @digorithm to land the awesome work in https://github.com/FuelLabs/forc-wallet/pull/3 which has long since been unblocked with plugin support and wallet support in the SDK.

Before beginning work on this, we should first address #2412.

## TODO

- [x] #2412 
- [x] Ensure we can add a wallet with `forc-wallet` CLI. https://github.com/FuelLabs/forc-wallet/issues/13.
- [x] Ensure we can use the created wallet to create a transaction within the deploy command. https://github.com/FuelLabs/forc-wallet/issues/5.
- [x] Manually sign the transaction with the `forc-wallet` CLI. https://github.com/FuelLabs/forc-wallet/issues/7.
- [x] ~~Paste the result back into `forc deploy`.~~

## Follow-up

- [ ] Add a flag that allows for bypassing the manual input and use some default wallet dedicated to testing.
- [ ] Consider using `forc-wallet` as a library within `forc deploy` to ease the process of selecting a wallet and signing the transaction. This *might* not even be desirable depending on how involved the signing process becomes in the wallet CLI as there will be many security issues to consider, and it might be safest to ensure they're dealt with in one place (the forc-wallet CLI).

**Comment by digorithm** [comment]
Awesome -- looking forward to this. 

Feel free to take over my forc-wallet PR in case it becomes a blocker and/or I'm busy with other work.

**Comment by mitchmindtree** [comment]
Closed as of #2641
