### ISSUE TITLE
[Tracking] feat(fmt): rewrite comment formatting

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/sway#3938]
_See #3789 for detailed discussion on handling comment formatting differently_

## Problem

The current way of formatting comments has led to a couple of small issues (#2933, #3853, #2888). This is mainly by design - the current way of formatting relies on inserting comments on a second pass after formatting the source code separately on a first pass, matching between formatted and unformatted source code and finding where to insert comments.

This can be hard to reason about, since we lose context of the formatter at the first pass of formatting - we lose useful information like indentation and width.

## Proposal

The original suggestion by @mitchmindtree was to implement a `Visitor`:

> This approach might be helped by splitting the Format trait into Visitor and Format traits, separating the logic for traversing the nodes from the logic for formatting them...

However our `Format` implementation is already acting as a Visitor! So I went with this approach:

> 1) we used to initialize the CommentMap at the comment insertion step. Instead, lets do it right before formatting now, and have the Formatter hold it as a &mut CommentMap
> 2) we then begin formatting. However, we do not implement FmtVisitor - I realized that it isn't really a useful abstraction at the moment. Instead I have a helper function that finds the comments within the comment map that are between a given start and end point - this can be between the end of a preceding span and a start of a following span. This has been particularly useful in certain cases that were hard to format before, like comments between } and else.
> 3)  we format the node there and then with the comment, and remove the entry from the CommentMap. This mutated CommentMap is later passed to handle_comments() which will format the remaining comments without the already formatted comment. This makes it so we can incrementally introduce the new pattern while still allowing us to use our old way of comment insertion.

This way, we can work on the new way of formatting comments, **while** still using the current way of formatting comments.

## Changes

The above proposal means that we would have to include comment formatting in every `Item` that implements `Format` that would likely have a comment on the previous line, or trailing it. To facilitate this i'm grouping things according to the original swayfmtv2 issue #1516:

- [ ] imports: ItemUse
- [ ] deps: Dependency, DependencyPath
- [ ] literals: Literal
- [ ] expressions: Expr, ExprStructField, ExprTupleDescriptor, ExprArrayDescriptor
- [x] abi: ItemAbi, AbiCastArgs
- [ ] asm: AsmBlock, AsmRegisterDeclaration, AsmBlockContents, AsmFinalExpr
- [ ] fn: ItemFn, FnSignature, FnArg
- [ ] match: MatchBranch, MatchBranchKind
- [ ] where: WhereClause, WhereBound
- [ ] ty: Ty, TyArrayDescriptor, TyTupleDescriptor
- [ ] Ident
- [ ] TypeField
- [ ] StorageField
- [ ] Statement
- [ ] CodeBlockContents
- [ ] Module
- [ ] IfExpr
- [ ] IfCondition
- [ ] Assignable
- [ ] ReassignmentOp
- [ ] Instruction
- [ ] PathExpr
- [ ] PathExprSegment
- [ ] QualifiedPathRoot
- [ ] PathType
- [ ] PathTypeSegment
- [ ] AttributeDecl
- [ ] GenericParams
- [ ] GenericArgs
- [ ] Pattern
- [ ] PatternStructField
- [ ] ItemImpl
- [ ] UseTree
- [ ] ItemTrait
- [ ] Traits
- [ ] ItemConst
- [ ] ItemStorage
- [ ] ItemStruct
- [ ] ItemEnum

## Testing

To make sure that changes made actually work as intended, I am planning to comment out `handle_comments()` to run selected tests.
