### ISSUE TITLE
Epic: refactor `low_level_call.sw`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5342]
It's a UX nightmare.
There's too many arguments and verbose names.

- [ ] CallParams::new(asset_id, coins, gas) method
- [ ] Rename `CallParams` to `CallArgs`
- [ ] Deprecate `call_with_function_selector_vec`
- [ ] `LowLevelCall` struct
