### ISSUE TITLE
Sway 1.0.0 tracking issue

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#5886]
- [ ] const fn
- [ ] closures and function pointers
- [ ] solution to impl coherence
- [ ] full References RFC implementation
- [ ] storage v3 with closures
- [ ] ranges
- [ ] full support for common iterators in std
- [ ] parser rewrite and full grammar specification
- [ ] char type and unckecked UTF-8 manipulation
- [ ] recursion
- [ ] type recursion
- [ ] clear rules for copy semantics
- [ ] refactor of our namespace implementation
- [ ] stabilized encoding v1
- [ ] full AST reordering
- [ ] remove all usages of Unknown in the type system
- [ ] escape codes in string literals
- [ ] benchmarking infrastructure
- [ ] tooling to survey community sway code
- [ ] crashdumps, bug triage and improved bug communication
- [ ] make storage and configurables visible in whole package
- [ ] move to developping behind experimental flags for features and only land bugfixes directly in the compiler
- [ ] make core/std split non arbitrary
- [ ] support `#[allow()]`, `#[warn()]` and `#[error()]` for all compiler messages
