### ISSUE TITLE
Incremental Compilation: Tracking issue.

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#6230]
* [ ] https://github.com/FuelLabs/sway/issues/6228
* [ ] https://github.com/FuelLabs/sway/issues/6227
* [ ] https://github.com/FuelLabs/sway/issues/6229
